[mypy]
ignore_missing_imports = True
strict = True
disallow_untyped_calls = False
disallow_untyped_defs = True
disallow_incomplete_defs = True
disallow_untyped_decorators = False
explicit_package_bases = True

plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "conf.settings"

[mypy-*.migrations.*]
; Django migrations should not produce any errors:
ignore_errors = True

; override settings for files starting with tests_ prefix
[mypy-tests.*]
strict = False
disallow_untyped_defs = False

[mypy-ors.*]
ignore_missing_imports = True
