# Generated by Django 6.0.3 on 2026-04-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_stackicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('gitlab', 'GitLab'), ('github', 'GitHub'), ('git', 'Git'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('nextjs', 'Next.js'), ('react', 'React'), ('nodejs', 'Node.js'), ('postgresql', 'PostgreSQL'), ('postgres', 'PostgreSQL'), ('redis', 'Redis'), ('tailwind', 'Tailwind CSS'), ('html', 'HTML'), ('css', 'CSS'), ('aws', 'AWS'), ('nginx', 'Nginx'), ('linux', 'Linux'), ('bash', 'Bash'), ('graphql', 'GraphQL'), ('rest', 'REST API'), ('mongodb', 'MongoDB'), ('mysql', 'MySQL')], max_length=100, unique=True)),
                ('icon_text', models.CharField(blank=True, default='', max_length=100, verbose_name='Optional text to display next to the icon')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
