# Generated by Django 6.0.3 on 2026-04-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stackicon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
