# Generated by Django 6.0.3 on 2026-04-07 08:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('work', 'Berufliche Erfahrung'), ('education', 'Ausbildung')], max_length=20)),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, help_text='Leer lassen für laufende Positionen', null=True, verbose_name='Enddatum')),
                ('organization', models.CharField(max_length=200, verbose_name='Firma/Institution')),
                ('position', models.CharField(max_length=200, verbose_name='Position/Rolle')),
                ('stack', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('gitlab', 'GitLab'), ('github', 'GitHub'), ('git', 'Git'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('nextjs', 'Next.js'), ('react', 'React'), ('nodejs', 'Node.js'), ('postgresql', 'PostgreSQL'), ('postgres', 'PostgreSQL'), ('redis', 'Redis'), ('tailwind', 'Tailwind CSS'), ('html', 'HTML'), ('css', 'CSS'), ('aws', 'AWS'), ('nginx', 'Nginx'), ('linux', 'Linux'), ('bash', 'Bash'), ('graphql', 'GraphQL'), ('rest', 'REST API'), ('mongodb', 'MongoDB'), ('mysql', 'MySQL'), ('c', 'C'), ('c++', 'C++'), ('c#', 'C#'), ('mathematica', 'Mathematica'), ('matlab', 'MATLAB')], max_length=100), blank=True, default=list, verbose_name='Verwendete Technologien')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.AlterField(
            model_name='stackicon',
            name='icon',
            field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('gitlab', 'GitLab'), ('github', 'GitHub'), ('git', 'Git'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('nextjs', 'Next.js'), ('react', 'React'), ('nodejs', 'Node.js'), ('postgresql', 'PostgreSQL'), ('postgres', 'PostgreSQL'), ('redis', 'Redis'), ('tailwind', 'Tailwind CSS'), ('html', 'HTML'), ('css', 'CSS'), ('aws', 'AWS'), ('nginx', 'Nginx'), ('linux', 'Linux'), ('bash', 'Bash'), ('graphql', 'GraphQL'), ('rest', 'REST API'), ('mongodb', 'MongoDB'), ('mysql', 'MySQL'), ('c', 'C'), ('c++', 'C++'), ('c#', 'C#'), ('mathematica', 'Mathematica'), ('matlab', 'MATLAB')], max_length=100, unique=True),
        ),
    ]
