# Generated by Django 6.0.3 on 2026-04-07 12:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_experience_alter_stackicon_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='stack',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('gitlab', 'GitLab'), ('github', 'GitHub'), ('git', 'Git'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('nextjs', 'Next.js'), ('react', 'React'), ('nodejs', 'Node.js'), ('postgres', 'PostgreSQL'), ('redis', 'Redis'), ('tailwind', 'Tailwind CSS'), ('html', 'HTML'), ('css', 'CSS'), ('aws', 'AWS'), ('nginx', 'Nginx'), ('linux', 'Linux'), ('bash', 'Bash'), ('graphql', 'GraphQL'), ('rest', 'REST API'), ('mongodb', 'MongoDB'), ('mysql', 'MySQL'), ('c', 'C'), ('c++', 'C++'), ('c#', 'C#'), ('mathematica', 'Mathematica'), ('matlab', 'MATLAB'), ('r', 'R'), ('java', 'Java')], max_length=100), blank=True, default=list, verbose_name='Verwendete Technologien'),
        ),
        migrations.AlterField(
            model_name='stackicon',
            name='icon',
            field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('gitlab', 'GitLab'), ('github', 'GitHub'), ('git', 'Git'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('nextjs', 'Next.js'), ('react', 'React'), ('nodejs', 'Node.js'), ('postgres', 'PostgreSQL'), ('redis', 'Redis'), ('tailwind', 'Tailwind CSS'), ('html', 'HTML'), ('css', 'CSS'), ('aws', 'AWS'), ('nginx', 'Nginx'), ('linux', 'Linux'), ('bash', 'Bash'), ('graphql', 'GraphQL'), ('rest', 'REST API'), ('mongodb', 'MongoDB'), ('mysql', 'MySQL'), ('c', 'C'), ('c++', 'C++'), ('c#', 'C#'), ('mathematica', 'Mathematica'), ('matlab', 'MATLAB'), ('r', 'R'), ('java', 'Java')], max_length=100, unique=True),
        ),
    ]
